### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jonathan-klh** [jonathan-klh/makeyourshop#2]
La page profile /app_dev.php/profile/ n'hérite pas du layout de l'application

**Comment by jonathan-klh** [comment]
La nav bug sur la homepage. Scroll a check

**Comment by god-zi** [comment]
C'est corrigé pour la page profile j'ai en même temps créé le fichier .gitignore le tout est sur la branch dev

**Comment by jonathan-klh** [comment]
bien joué, push ?
